Add authority_map feature
rciam/simplesamlphp-module-userid pull request #14
Opened 2021-05-07 11:25 UTC by nikosev

2021-05-07 11:26 UTC, NicolasLiampotis commented on CHANGELOG.md
> +- Replace modified entityIDs with the old ones
Add support for migrating users from IdPs with updated entityID

2021-05-07 11:29 UTC, NicolasLiampotis requested changes

2021-05-07 11:29 UTC, NicolasLiampotis commented on lib/Auth/Process/OpaqueSmartID.php
> +                Logger::debug(
change to info

2021-05-07 14:56 UTC, nikosev commented on CHANGELOG.md
> +- Replace modified entityIDs with the old ones
resolved by commit [Update CHANGELOG description for authority_map feature](https://github.com/rciam/simplesamlphp-module-userid/pull/14/commits/115c988fc90ef93fde2f7f2e7e8a37b36e2c2980)

2021-05-07 14:57 UTC, nikosev commented on lib/Auth/Process/OpaqueSmartID.php
> +                Logger::debug(
resolved by commit [Change log lever when the module is using an entityID from authorityMap](https://github.com/rciam/simplesamlphp-module-userid/pull/14/commits/7166c21ee53c68266ef8eb9519bd44cb6b9274fa)

2021-05-10 00:04 UTC, NicolasLiampotis approved these changes
LGTM

2021-05-10 00:05 UTC, merged